# Generated by Django 3.2.9 on 2021-12-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='quiz',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ответы на Вопросы'),
        ),
    ]
