# Generated by Django 3.2.9 on 2021-12-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_servicerequest_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='quiz',
            new_name='comment',
        ),
    ]
