# Generated by Django 3.2.9 on 2021-12-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_quiz_servicerequest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
    ]
